{
  imports = [
    ./podman
    ./caddy.nix
    ./backup.nix
    ./radicale.nix
    ./syncthing.nix
    ./copyparty.nix
    ./zfs.nix
    ./matter-server.nix
    ./home-assistant.nix
    ./esphome.nix
    ./blocky.nix
    ./monitoring.nix
    ./ntfy.nix
    ./miniflux.nix
    ../common/house-keeping.nix 
 ];
}
